name: IAST CI/CD 

on: [push, pull_request, workflow_dispatch]

jobs:
  launch-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Install New Relic agent
        run: |
          npm install "https://github.com/k2io/node-newrelic-fork/#ci_support"

      - name: Configure New Relic agent
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_APP_NAME: My Express App
          NEW_RELIC_SECURITY_IAST_TEST_IDENTIFIER: ${{ github.run_id }}
        run: |
          echo "NEW_RELIC_LICENSE_KEY=$NEW_RELIC_LICENSE_KEY" >> .env
          echo "NEW_RELIC_APP_NAME=$NEW_RELIC_APP_NAME" >> .env
          echo "NEW_RELIC_SECURITY_IAST_TEST_IDENTIFIER=$NEW_RELIC_SECURITY_IAST_TEST_IDENTIFIER" >> .env

      - name: Start Express app with New Relic agent
        run: |
          node index.js /dev/null 2>&1 &
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_APP_NAME: My Express App
          NEW_RELIC_SECURITY_IAST_TEST_IDENTIFIER: ${{ github.run_id }}

      - name: Wait for 30 seconds
        run: |
          sleep 30

      - name: Fire HTTP request to the application
        uses: fjogeleit/http-request-action@v1
        id: http
        with:
          url: 'http://localhost:3000/rce/attack?payload=ls'
          method: 'GET'

      - name: Print response
        run: |
          echo "Response status code: ${{ steps.http.outputs.status }}"
          echo "Response body: ${{ steps.http.outputs.response }}"
      
      - name: Execute curl command
        run: |
          curl https://example.com

      - name: Wait for 300 seconds
        run: |
          sleep 300
      
